build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

spring:
  database:
    driverClassName:  org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: "postgres"
    password: "p@ssw0rd"
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always