build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371

spring:
  database:
    driverClassName:  org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: "postgres"
    password: "p@ssw0rd"
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always