build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loansdb
    username: root
    password: p@ssw0rd
  jpa:
    show-sql: true
  sql:
    init:
      mode: always